# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.credentials4 import Credentials4

class TestCredentials4(unittest.TestCase):
    """Credentials4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Credentials4:
        """Test Credentials4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Credentials4`
        """
        model = Credentials4()
        if include_optional:
            return Credentials4(
                type = 'key_pair',
                username = '',
                private_key = '',
                private_key_passphrase = '',
                password = ''
            )
        else:
            return Credentials4(
                username = '',
                private_key = '',
                password = '',
        )
        """

    def testCredentials4(self):
        """Test Credentials4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
