# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.httpapi_config import HTTPAPIConfig

class TestHTTPAPIConfig(unittest.TestCase):
    """HTTPAPIConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTPAPIConfig:
        """Test HTTPAPIConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTTPAPIConfig`
        """
        model = HTTPAPIConfig()
        if include_optional:
            return HTTPAPIConfig(
                provider_type = 'http_api',
                credentials = mixpeek.models.httpapi_header_credentials.HTTPAPIHeaderCredentials(
                    type = 'http_headers', 
                    headers = {
                        'key' : ''
                        }, ),
                http_method = 'GET',
                request_body = { },
                items_path = '',
                item_id_field = '',
                item_modified_field = '',
                response_content_type = 'json',
                user_agent = 'Mixpeek HTTP API Sync/1.0',
                request_timeout = 5
            )
        else:
            return HTTPAPIConfig(
                item_id_field = '',
        )
        """

    def testHTTPAPIConfig(self):
        """Test HTTPAPIConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
