# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.create_retriever_request import CreateRetrieverRequest

class TestCreateRetrieverRequest(unittest.TestCase):
    """CreateRetrieverRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRetrieverRequest:
        """Test CreateRetrieverRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRetrieverRequest`
        """
        model = CreateRetrieverRequest()
        if include_optional:
            return CreateRetrieverRequest(
                retriever_name = '',
                description = '',
                input_schema = { },
                collection_ids = [
                    ''
                    ],
                stages = [
                    mixpeek.models.stage_instance_config.StageInstanceConfig(
                        stage_name = '', 
                        version = '', 
                        parameters = { }, 
                        pre_filters = { }, 
                        post_filters = { }, 
                        stats = mixpeek.models.stage_performance.StagePerformance(
                            avg_execution_ms = 1.337, 
                            execution_count = 56, 
                            error_count = 56, 
                            last_executed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ],
                metadata = { },
                tags = [
                    ''
                    ],
                enabled = True
            )
        else:
            return CreateRetrieverRequest(
                retriever_name = '',
                input_schema = { },
                collection_ids = [
                    ''
                    ],
                stages = [
                    mixpeek.models.stage_instance_config.StageInstanceConfig(
                        stage_name = '', 
                        version = '', 
                        parameters = { }, 
                        pre_filters = { }, 
                        post_filters = { }, 
                        stats = mixpeek.models.stage_performance.StagePerformance(
                            avg_execution_ms = 1.337, 
                            execution_count = 56, 
                            error_count = 56, 
                            last_executed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ],
        )
        """

    def testCreateRetrieverRequest(self):
        """Test CreateRetrieverRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
