# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.cluster_centroid import ClusterCentroid

class TestClusterCentroid(unittest.TestCase):
    """ClusterCentroid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterCentroid:
        """Test ClusterCentroid
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterCentroid`
        """
        model = ClusterCentroid()
        if include_optional:
            return ClusterCentroid(
                cluster_id = '',
                centroid_vector = [
                    1.337
                    ],
                feature_name = '',
                feature_dimensions = 56,
                num_members = 56,
                variance = 1.337,
                label = '',
                summary = '',
                keywords = [
                    ''
                    ],
                effective_features = { },
                feature_statistics = {
                    'key' : {
                        'key' : 1.337
                        }
                    },
                parent_cluster_id = '',
                child_cluster_ids = [
                    ''
                    ],
                hierarchy_level = 56,
                metadata = { }
            )
        else:
            return ClusterCentroid(
                cluster_id = '',
                centroid_vector = [
                    1.337
                    ],
                feature_name = '',
                feature_dimensions = 56,
        )
        """

    def testClusterCentroid(self):
        """Test ClusterCentroid"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
