# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.api.pages_api import PagesApi


class TestPagesApi(unittest.TestCase):
    """PagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PagesApi()

    def tearDown(self) -> None:
        pass

    def test_create_page(self) -> None:
        """Test case for create_page

        Create a Page
        """
        pass

    def test_delete_page(self) -> None:
        """Test case for delete_page

        Delete a Page
        """
        pass

    def test_get_page(self) -> None:
        """Test case for get_page

        Get a Page
        """
        pass

    def test_list_pages(self) -> None:
        """Test case for list_pages

        List Pages
        """
        pass

    def test_update_page(self) -> None:
        """Test case for update_page

        Update a Page
        """
        pass


if __name__ == '__main__':
    unittest.main()
