# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.stage_defs_document_query_input import StageDefsDocumentQueryInput

class TestStageDefsDocumentQueryInput(unittest.TestCase):
    """StageDefsDocumentQueryInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StageDefsDocumentQueryInput:
        """Test StageDefsDocumentQueryInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StageDefsDocumentQueryInput`
        """
        model = StageDefsDocumentQueryInput()
        if include_optional:
            return StageDefsDocumentQueryInput(
                input_mode = 'document',
                document_ref = mixpeek.models.document_reference.DocumentReference(
                    collection_id = '', 
                    document_id = '', )
            )
        else:
            return StageDefsDocumentQueryInput(
                document_ref = mixpeek.models.document_reference.DocumentReference(
                    collection_id = '', 
                    document_id = '', ),
        )
        """

    def testStageDefsDocumentQueryInput(self):
        """Test StageDefsDocumentQueryInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
