# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.list_namespaces_response import ListNamespacesResponse

class TestListNamespacesResponse(unittest.TestCase):
    """ListNamespacesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListNamespacesResponse:
        """Test ListNamespacesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListNamespacesResponse`
        """
        model = ListNamespacesResponse()
        if include_optional:
            return ListNamespacesResponse(
                results = [
                    mixpeek.models.namespace_model.NamespaceModel(
                        namespace_id = '', 
                        namespace_name = 'spotify_playlists_dev', 
                        description = '', 
                        feature_extractors = [
                            mixpeek.models.base_feature_extractor_model.BaseFeatureExtractorModel(
                                feature_extractor_name = '', 
                                version = '', 
                                feature_extractor_id = '', )
                            ], 
                        payload_indexes = [
                            mixpeek.models.payload_index_config.PayloadIndexConfig(
                                field_name = '', 
                                type = 'keyword', 
                                field_schema = null, )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = mixpeek.models.pagination_response.PaginationResponse(
                    total = 56, 
                    page = 56, 
                    page_size = 56, 
                    total_pages = 56, 
                    next_page = '', 
                    previous_page = '', ),
                total_count = 56
            )
        else:
            return ListNamespacesResponse(
                results = [
                    mixpeek.models.namespace_model.NamespaceModel(
                        namespace_id = '', 
                        namespace_name = 'spotify_playlists_dev', 
                        description = '', 
                        feature_extractors = [
                            mixpeek.models.base_feature_extractor_model.BaseFeatureExtractorModel(
                                feature_extractor_name = '', 
                                version = '', 
                                feature_extractor_id = '', )
                            ], 
                        payload_indexes = [
                            mixpeek.models.payload_index_config.PayloadIndexConfig(
                                field_name = '', 
                                type = 'keyword', 
                                field_schema = null, )
                            ], 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                pagination = mixpeek.models.pagination_response.PaginationResponse(
                    total = 56, 
                    page = 56, 
                    page_size = 56, 
                    total_pages = 56, 
                    next_page = '', 
                    previous_page = '', ),
                total_count = 56,
        )
        """

    def testListNamespacesResponse(self):
        """Test ListNamespacesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
