# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.rss_http_header_credentials import RSSHttpHeaderCredentials

class TestRSSHttpHeaderCredentials(unittest.TestCase):
    """RSSHttpHeaderCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RSSHttpHeaderCredentials:
        """Test RSSHttpHeaderCredentials
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RSSHttpHeaderCredentials`
        """
        model = RSSHttpHeaderCredentials()
        if include_optional:
            return RSSHttpHeaderCredentials(
                type = 'http_headers',
                headers = {
                    'key' : ''
                    }
            )
        else:
            return RSSHttpHeaderCredentials(
        )
        """

    def testRSSHttpHeaderCredentials(self):
        """Test RSSHttpHeaderCredentials"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
