# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.llm_labeling import LLMLabeling

class TestLLMLabeling(unittest.TestCase):
    """LLMLabeling unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LLMLabeling:
        """Test LLMLabeling
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LLMLabeling`
        """
        model = LLMLabeling()
        if include_optional:
            return LLMLabeling(
                enabled = True,
                provider = 'openai',
                model_name = '',
                include_summary = True,
                include_keywords = True,
                max_samples_per_cluster = 56,
                custom_prompt = '',
                parameters = { }
            )
        else:
            return LLMLabeling(
        )
        """

    def testLLMLabeling(self):
        """Test LLMLabeling"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
