# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.api.documents_api import DocumentsApi


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentsApi()

    def tearDown(self) -> None:
        pass

    def test_get_document_ns(self) -> None:
        """Test case for get_document_ns

        Get a document by ID (namespace-scoped).
        """
        pass

    def test_patch_document_ns(self) -> None:
        """Test case for patch_document_ns

        Partially update a document by ID (namespace-scoped).
        """
        pass

    def test_update_document_ns(self) -> None:
        """Test case for update_document_ns

        Update a document by ID (namespace-scoped).
        """
        pass


if __name__ == '__main__':
    unittest.main()
