# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.cluster_member import ClusterMember

class TestClusterMember(unittest.TestCase):
    """ClusterMember unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterMember:
        """Test ClusterMember
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterMember`
        """
        model = ClusterMember()
        if include_optional:
            return ClusterMember(
                document_id = '',
                cluster_id = '',
                distance_to_centroid = 1.337,
                coordinates = [
                    1.337
                    ],
                source_details = mixpeek.models.source_details.SourceDetails(
                    type = 'bucket', 
                    source_id = '', ),
                features = { }
            )
        else:
            return ClusterMember(
                document_id = '',
                cluster_id = '',
                distance_to_centroid = 1.337,
                coordinates = [
                    1.337
                    ],
                source_details = mixpeek.models.source_details.SourceDetails(
                    type = 'bucket', 
                    source_id = '', ),
        )
        """

    def testClusterMember(self):
        """Test ClusterMember"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
