# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.parameters_value import ParametersValue

class TestParametersValue(unittest.TestCase):
    """ParametersValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ParametersValue:
        """Test ParametersValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ParametersValue`
        """
        model = ParametersValue()
        if include_optional:
            return ParametersValue(
                type = 'fixed',
                value = None
            )
        else:
            return ParametersValue(
                type = 'fixed',
                value = None,
        )
        """

    def testParametersValue(self):
        """Test ParametersValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
