# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.marketplace_listing import MarketplaceListing

class TestMarketplaceListing(unittest.TestCase):
    """MarketplaceListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplaceListing:
        """Test MarketplaceListing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplaceListing`
        """
        model = MarketplaceListing()
        if include_optional:
            return MarketplaceListing(
                listing_id = '',
                internal_id = '',
                namespace_id = '',
                retriever_id = '',
                title = '',
                description = '',
                public_name = '012',
                category = '',
                tags = [
                    ''
                    ],
                logo_url = '',
                icon_base64 = '',
                available_tiers = [
                    mixpeek.models.subscription_tier_config.SubscriptionTierConfig(
                        tier = 'free', 
                        price_per_month = 0, 
                        limits = mixpeek.models.tier_limits.TierLimits(
                            requests_per_minute = 56, 
                            requests_per_hour = 56, 
                            requests_per_day = 56, 
                            requests_per_month = 56, ), 
                        features = [
                            ''
                            ], 
                        stripe_price_id = '', )
                    ],
                display_config = { },
                password_secret_name = '',
                status = 'draft',
                visibility = 'listed',
                is_active = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_subscribers = 56,
                total_queries = 56
            )
        else:
            return MarketplaceListing(
                internal_id = '',
                namespace_id = '',
                retriever_id = '',
                title = '',
                description = '',
                public_name = '012',
                available_tiers = [
                    mixpeek.models.subscription_tier_config.SubscriptionTierConfig(
                        tier = 'free', 
                        price_per_month = 0, 
                        limits = mixpeek.models.tier_limits.TierLimits(
                            requests_per_minute = 56, 
                            requests_per_hour = 56, 
                            requests_per_day = 56, 
                            requests_per_month = 56, ), 
                        features = [
                            ''
                            ], 
                        stripe_price_id = '', )
                    ],
        )
        """

    def testMarketplaceListing(self):
        """Test MarketplaceListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
