# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.enrichments import Enrichments

class TestEnrichments(unittest.TestCase):
    """Enrichments unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Enrichments:
        """Test Enrichments
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Enrichments`
        """
        model = Enrichments()
        if include_optional:
            return Enrichments(
                clusters = [
                    mixpeek.models.cluster_member.ClusterMember(
                        document_id = '', 
                        cluster_id = '', 
                        distance_to_centroid = 1.337, 
                        coordinates = [
                            1.337
                            ], 
                        source_details = mixpeek.models.source_details.SourceDetails(
                            type = 'bucket', 
                            source_id = '', ), 
                        features = { }, )
                    ],
                taxonomies = [
                    mixpeek.models.taxonomy_assignment.TaxonomyAssignment(
                        taxonomy_id = '', 
                        node_id = '', 
                        path = [
                            ''
                            ], 
                        label = '', 
                        score = 1.337, )
                    ]
            )
        else:
            return Enrichments(
        )
        """

    def testEnrichments(self):
        """Test Enrichments"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
