# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.lint_response import LintResponse

class TestLintResponse(unittest.TestCase):
    """LintResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LintResponse:
        """Test LintResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LintResponse`
        """
        model = LintResponse()
        if include_optional:
            return LintResponse(
                valid = True,
                results = [
                    mixpeek.models.lint_result.LintResult(
                        code = '', 
                        severity = 'error', 
                        message = '', 
                        location = '', 
                        suggestion = '', 
                        fix_example = '', )
                    ],
                summary = {
                    'key' : 56
                    }
            )
        else:
            return LintResponse(
                valid = True,
        )
        """

    def testLintResponse(self):
        """Test LintResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
