# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.vector_based_config import VectorBasedConfig

class TestVectorBasedConfig(unittest.TestCase):
    """VectorBasedConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VectorBasedConfig:
        """Test VectorBasedConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VectorBasedConfig`
        """
        model = VectorBasedConfig()
        if include_optional:
            return VectorBasedConfig(
                feature_extractor_name = '',
                clustering_method = 'kmeans',
                sample_size = 56,
                kmeans_parameters = None,
                dbscan_parameters = None,
                hdbscan_parameters = None,
                algorithm_params = None
            )
        else:
            return VectorBasedConfig(
                feature_extractor_name = '',
                clustering_method = 'kmeans',
        )
        """

    def testVectorBasedConfig(self):
        """Test VectorBasedConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
