# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.stage_defs_feature_search_group_by import StageDefsFeatureSearchGroupBy

class TestStageDefsFeatureSearchGroupBy(unittest.TestCase):
    """StageDefsFeatureSearchGroupBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StageDefsFeatureSearchGroupBy:
        """Test StageDefsFeatureSearchGroupBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StageDefsFeatureSearchGroupBy`
        """
        model = StageDefsFeatureSearchGroupBy()
        if include_optional:
            return StageDefsFeatureSearchGroupBy(
                var_field = '',
                max_per_group = 1,
                limit = 1,
                output_mode = 'all'
            )
        else:
            return StageDefsFeatureSearchGroupBy(
                var_field = '',
        )
        """

    def testStageDefsFeatureSearchGroupBy(self):
        """Test StageDefsFeatureSearchGroupBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
