# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.cluster_data_response import ClusterDataResponse

class TestClusterDataResponse(unittest.TestCase):
    """ClusterDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterDataResponse:
        """Test ClusterDataResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterDataResponse`
        """
        model = ClusterDataResponse()
        if include_optional:
            return ClusterDataResponse(
                cluster_id = '',
                centroids = [
                    mixpeek.models.cluster_centroid_data.ClusterCentroidData(
                        cluster_label = '', 
                        centroid_vector = [
                            1.337
                            ], 
                        num_members = 56, 
                        metadata = { }, )
                    ],
                members = [
                    mixpeek.models.cluster_member_data.ClusterMemberData(
                        document_id = '', 
                        cluster_label = '', 
                        distance_to_centroid = 1.337, 
                        coordinates = [
                            1.337
                            ], 
                        metadata = { }, )
                    ],
                total_clusters = 56,
                total_members = 56
            )
        else:
            return ClusterDataResponse(
                cluster_id = '',
                total_clusters = 56,
                total_members = 56,
        )
        """

    def testClusterDataResponse(self):
        """Test ClusterDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
