# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.flat_taxonomy_config_input import FlatTaxonomyConfigInput

class TestFlatTaxonomyConfigInput(unittest.TestCase):
    """FlatTaxonomyConfigInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlatTaxonomyConfigInput:
        """Test FlatTaxonomyConfigInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlatTaxonomyConfigInput`
        """
        model = FlatTaxonomyConfigInput()
        if include_optional:
            return FlatTaxonomyConfigInput(
                taxonomy_type = 'flat',
                retriever_id = '',
                input_mappings = [
                    mixpeek.models.input_mapping.InputMapping(
                        input_key = '', 
                        source_type = 'payload', 
                        path = '', 
                        override = null, )
                    ],
                source_collection = mixpeek.models.source_collection.SourceCollection(
                    collection_id = '', 
                    enrichment_fields = [
                        mixpeek.models.enrichment_field.EnrichmentField(
                            field_path = '', 
                            merge_mode = 'replace', )
                        ], )
            )
        else:
            return FlatTaxonomyConfigInput(
                retriever_id = '',
                input_mappings = [
                    mixpeek.models.input_mapping.InputMapping(
                        input_key = '', 
                        source_type = 'payload', 
                        path = '', 
                        override = null, )
                    ],
                source_collection = mixpeek.models.source_collection.SourceCollection(
                    collection_id = '', 
                    enrichment_fields = [
                        mixpeek.models.enrichment_field.EnrichmentField(
                            field_path = '', 
                            merge_mode = 'replace', )
                        ], ),
        )
        """

    def testFlatTaxonomyConfigInput(self):
        """Test FlatTaxonomyConfigInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
