# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.cluster_data_request import ClusterDataRequest

class TestClusterDataRequest(unittest.TestCase):
    """ClusterDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClusterDataRequest:
        """Test ClusterDataRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterDataRequest`
        """
        model = ClusterDataRequest()
        if include_optional:
            return ClusterDataRequest(
                cluster_id = '',
                include_centroids = True,
                include_members = True,
                limit = 56,
                offset = 56
            )
        else:
            return ClusterDataRequest(
        )
        """

    def testClusterDataRequest(self):
        """Test ClusterDataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
