# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.api.retriever_api_keys_api import RetrieverAPIKeysApi


class TestRetrieverAPIKeysApi(unittest.TestCase):
    """RetrieverAPIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RetrieverAPIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_retriever_key(self) -> None:
        """Test case for create_retriever_key

        Create Retriever API Key
        """
        pass

    def test_list_retriever_keys(self) -> None:
        """Test case for list_retriever_keys

        List Retriever API Keys
        """
        pass

    def test_revoke_retriever_key(self) -> None:
        """Test case for revoke_retriever_key

        Revoke Retriever API Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
