# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.credentials1 import Credentials1

class TestCredentials1(unittest.TestCase):
    """Credentials1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Credentials1:
        """Test Credentials1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Credentials1`
        """
        model = Credentials1()
        if include_optional:
            return Credentials1(
                type = 'service_account',
                project_id = '',
                private_key_id = '',
                private_key = '',
                client_email = '',
                client_id = '',
                client_secret = '',
                refresh_token = ''
            )
        else:
            return Credentials1(
                project_id = '',
                private_key_id = '',
                private_key = '',
                client_email = '',
                client_id = '',
                client_secret = '',
                refresh_token = '',
        )
        """

    def testCredentials1(self):
        """Test Credentials1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
