# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_key_organizations_users_email(self) -> None:
        """Test case for create_key_organizations_users_email

        Create Api Key
        """
        pass

    def test_delete_key_organizations_users_email_name(self) -> None:
        """Test case for delete_key_organizations_users_email_name

        Delete Api Key
        """
        pass

    def test_delete_user_organizations_email(self) -> None:
        """Test case for delete_user_organizations_email

        Delete User
        """
        pass

    def test_get_organization(self) -> None:
        """Test case for get_organization

        Get Organization
        """
        pass

    def test_get_user_organizations_email(self) -> None:
        """Test case for get_user_organizations_email

        Get User
        """
        pass

    def test_update_key_organizations_users_email_name(self) -> None:
        """Test case for update_key_organizations_users_email_name

        Update Api Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
