# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.execute_cluster_response import ExecuteClusterResponse

class TestExecuteClusterResponse(unittest.TestCase):
    """ExecuteClusterResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecuteClusterResponse:
        """Test ExecuteClusterResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExecuteClusterResponse`
        """
        model = ExecuteClusterResponse()
        if include_optional:
            return ExecuteClusterResponse(
                success = True,
                run_id = '',
                algorithm = 'kmeans',
                num_clusters = 56,
                num_documents = 56,
                centroids = [
                    mixpeek.models.cluster_centroid.ClusterCentroid(
                        cluster_id = '', 
                        centroid_vector = [
                            1.337
                            ], 
                        feature_name = '', 
                        feature_dimensions = 56, 
                        num_members = 56, 
                        variance = 1.337, 
                        label = '', 
                        summary = '', 
                        keywords = [
                            ''
                            ], 
                        effective_features = { }, 
                        feature_statistics = {
                            'key' : {
                                'key' : 1.337
                                }
                            }, 
                        parent_cluster_id = '', 
                        child_cluster_ids = [
                            ''
                            ], 
                        hierarchy_level = 56, 
                        metadata = { }, )
                    ],
                metrics = {
                    'key' : 1.337
                    },
                parquet_path = '',
                members_key = '',
                execution_time_ms = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ExecuteClusterResponse(
                success = True,
                algorithm = 'kmeans',
                num_clusters = 56,
                num_documents = 56,
                centroids = [
                    mixpeek.models.cluster_centroid.ClusterCentroid(
                        cluster_id = '', 
                        centroid_vector = [
                            1.337
                            ], 
                        feature_name = '', 
                        feature_dimensions = 56, 
                        num_members = 56, 
                        variance = 1.337, 
                        label = '', 
                        summary = '', 
                        keywords = [
                            ''
                            ], 
                        effective_features = { }, 
                        feature_statistics = {
                            'key' : {
                                'key' : 1.337
                                }
                            }, 
                        parent_cluster_id = '', 
                        child_cluster_ids = [
                            ''
                            ], 
                        hierarchy_level = 56, 
                        metadata = { }, )
                    ],
                execution_time_ms = 56,
        )
        """

    def testExecuteClusterResponse(self):
        """Test ExecuteClusterResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
