# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.user_model_input import UserModelInput

class TestUserModelInput(unittest.TestCase):
    """UserModelInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserModelInput:
        """Test UserModelInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserModelInput`
        """
        model = UserModelInput()
        if include_optional:
            return UserModelInput(
                user_id = '',
                user_name = '',
                email = '',
                api_keys = [
                    mixpeek.models.api_key.APIKey(
                        key = '', 
                        name = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        permissions = [
                            'read'
                            ], )
                    ],
                metadata = { },
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return UserModelInput(
                email = '',
        )
        """

    def testUserModelInput(self):
        """Test UserModelInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
