# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.api.discovery_api import DiscoveryApi


class TestDiscoveryApi(unittest.TestCase):
    """DiscoveryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DiscoveryApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_discovery(self) -> None:
        """Test case for get_all_discovery

        Get All Discovery Information
        """
        pass

    def test_get_manifest_schema_discovery(self) -> None:
        """Test case for get_manifest_schema_discovery

        Get Manifest Schema for Agent Configuration
        """
        pass

    def test_list_extractors_discovery(self) -> None:
        """Test case for list_extractors_discovery

        List Available Feature Extractors
        """
        pass

    def test_list_stages_with_examples_discovery(self) -> None:
        """Test case for list_stages_with_examples_discovery

        List Available Retriever Stages with Examples
        """
        pass


if __name__ == '__main__':
    unittest.main()
