# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.config import Config

class TestConfig(unittest.TestCase):
    """Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Config:
        """Test Config
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Config`
        """
        model = Config()
        if include_optional:
            return Config(
                taxonomy_type = 'hierarchical',
                retriever_id = '',
                input_mappings = [
                    mixpeek.models.input_mapping.InputMapping(
                        input_key = '', 
                        source_type = 'payload', 
                        path = '', 
                        override = null, )
                    ],
                source_collection = mixpeek.models.source_collection.SourceCollection(
                    collection_id = '', 
                    enrichment_fields = [
                        mixpeek.models.enrichment_field.EnrichmentField(
                            field_path = '', 
                            merge_mode = 'replace', )
                        ], ),
                inference_strategy = 'schema',
                inference_collections = [
                    ''
                    ],
                llm_provider = 'openai_chat_v1',
                llm_model = '',
                llm_prompt_template = '',
                llm_sample_size = 56,
                cluster_ids = [
                    ''
                    ],
                cluster_overlap_threshold = 1.337,
                hierarchical_nodes = [
                    mixpeek.models.hierarchical_node.HierarchicalNode(
                        collection_id = '', 
                        parent_collection_id = '', 
                        label = '', 
                        summary = '', 
                        keywords = [
                            ''
                            ], 
                        retriever_id = '', 
                        enrichment_fields = [
                            mixpeek.models.enrichment_field.EnrichmentField(
                                field_path = '', 
                                merge_mode = 'replace', )
                            ], 
                        input_mappings = [
                            mixpeek.models.input_mapping.InputMapping(
                                input_key = '', 
                                source_type = 'payload', 
                                path = '', 
                                override = null, )
                            ], )
                    ]
            )
        else:
            return Config(
                retriever_id = '',
                input_mappings = [
                    mixpeek.models.input_mapping.InputMapping(
                        input_key = '', 
                        source_type = 'payload', 
                        path = '', 
                        override = null, )
                    ],
                source_collection = mixpeek.models.source_collection.SourceCollection(
                    collection_id = '', 
                    enrichment_fields = [
                        mixpeek.models.enrichment_field.EnrichmentField(
                            field_path = '', 
                            merge_mode = 'replace', )
                        ], ),
        )
        """

    def testConfig(self):
        """Test Config"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
