# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.provider_config import ProviderConfig

class TestProviderConfig(unittest.TestCase):
    """ProviderConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProviderConfig:
        """Test ProviderConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProviderConfig`
        """
        model = ProviderConfig()
        if include_optional:
            return ProviderConfig(
                provider_type = 'box',
                credentials = None,
                shared_drive_id = '',
                impersonate_user = '',
                region = 'auto',
                endpoint_url = 'https://fly.storage.tigris.dev',
                use_ssl = True,
                verify_ssl = True,
                account = '',
                warehouse = '',
                database = '',
                var_schema = 'public',
                role = '',
                incremental_column = '',
                primary_key_columns = [
                    ''
                    ],
                query_timeout_seconds = 1,
                fetch_size = 100,
                site_id = '',
                drive_id = '',
                folder_path = '',
                host = '',
                port = 1,
                ssl_mode = 'prefer',
                scopes = [
                    ''
                    ],
                business_account_id = '',
                user_agent = 'Mixpeek HTTP API Sync/1.0',
                request_timeout = 5,
                http_method = 'GET',
                request_body = { },
                items_path = '',
                item_id_field = '',
                item_modified_field = '',
                response_content_type = 'json',
                folder_id = '0'
            )
        else:
            return ProviderConfig(
                credentials = None,
                region = 'auto',
                account = '',
                warehouse = '',
                database = '',
                host = '',
                item_id_field = '',
        )
        """

    def testProviderConfig(self):
        """Test ProviderConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
