# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mixpeek.models.stage_defs_aggregation_function import StageDefsAggregationFunction

class TestStageDefsAggregationFunction(unittest.TestCase):
    """StageDefsAggregationFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStageDefsAggregationFunction(self):
        """Test StageDefsAggregationFunction"""
        # inst = StageDefsAggregationFunction()

if __name__ == '__main__':
    unittest.main()
