# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BoxCCGCredentials(BaseModel):
    """
    Credentials for Box Client Credentials Grant (CCG) authentication.  CCG provides server-to-server authentication without user interaction. Recommended for enterprise and automated sync operations.  Prerequisites:     - Create a Box application with Server Authentication (Client Credentials Grant)     - Authorize the application in the Box Admin Console     - Optionally configure an enterprise or user ID to act as  Security:     - client_secret encrypted at rest via CSFLE     - No user tokens involved; app authenticates as itself or as a user/enterprise
    """ # noqa: E501
    type: Optional[StrictStr] = 'ccg'
    client_id: StrictStr = Field(description="REQUIRED. Box application client ID from Developer Console.")
    client_secret: StrictStr = Field(description="REQUIRED. Box application client secret. SECURITY: Encrypted at rest via CSFLE.")
    enterprise_id: Optional[StrictStr] = Field(default=None, description="Enterprise ID to authenticate as. Required when using CCG to act as the enterprise (service account). Find in: Box Admin Console > Enterprise Settings.")
    user_id: Optional[StrictStr] = Field(default=None, description="User ID to authenticate as. Used when the app needs to act as a specific managed user. Mutually exclusive with enterprise_id for token acquisition.")
    __properties: ClassVar[List[str]] = ["type", "client_id", "client_secret", "enterprise_id", "user_id"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ccg']):
            raise ValueError("must be one of enum values ('ccg')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BoxCCGCredentials from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BoxCCGCredentials from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type") if obj.get("type") is not None else 'ccg',
            "client_id": obj.get("client_id"),
            "client_secret": obj.get("client_secret"),
            "enterprise_id": obj.get("enterprise_id"),
            "user_id": obj.get("user_id")
        })
        return _obj


