# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mixpeek.models.trigger_execution_config import TriggerExecutionConfig
from mixpeek.models.trigger_status import TriggerStatus
from mixpeek.models.trigger_type import TriggerType
from typing import Optional, Set
from typing_extensions import Self

class CreateTriggerRequest(BaseModel):
    """
    Request to create a new trigger.
    """ # noqa: E501
    cluster_id: Optional[StrictStr] = Field(default=None, description="Optional existing cluster ID")
    execution_config: Optional[TriggerExecutionConfig] = Field(default=None, description="Required if cluster_id not provided")
    trigger_type: TriggerType = Field(description="Type of trigger")
    schedule_config: Dict[str, Any] = Field(description="Schedule configuration")
    description: Optional[StrictStr] = Field(default=None, description="Trigger description")
    status: Optional[TriggerStatus] = Field(default=None, description="Initial status")
    __properties: ClassVar[List[str]] = ["cluster_id", "execution_config", "trigger_type", "schedule_config", "description", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateTriggerRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of execution_config
        if self.execution_config:
            _dict['execution_config'] = self.execution_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateTriggerRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cluster_id": obj.get("cluster_id"),
            "execution_config": TriggerExecutionConfig.from_dict(obj["execution_config"]) if obj.get("execution_config") is not None else None,
            "trigger_type": obj.get("trigger_type"),
            "schedule_config": obj.get("schedule_config"),
            "description": obj.get("description"),
            "status": obj.get("status")
        })
        return _obj


