# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mixpeek.models.join_mode import JoinMode
from mixpeek.models.logical_operator_input import LogicalOperatorInput
from mixpeek.models.retriever_model_input import RetrieverModelInput
from mixpeek.models.taxonomy_model import TaxonomyModel
from typing import Optional, Set
from typing_extensions import Self

class ExecuteTaxonomyRequest(BaseModel):
    """
    Request model for on-demand taxonomy validation and testing.  NOTE: This endpoint only supports ON_DEMAND mode for testing/validation. Batch taxonomy materialization is automatically triggered by the engine after feature extraction completes, based on collection configuration.
    """ # noqa: E501
    taxonomy: TaxonomyModel = Field(description="Full taxonomy model with configuration (fetched from DB by controller)")
    retriever: Optional[RetrieverModelInput] = Field(default=None, description="Optional retriever configuration override for testing. If omitted, uses the retriever configured in the taxonomy.")
    source_documents: Optional[List[Dict[str, Any]]] = Field(default=None, description="Optional documents to enrich for testing. If omitted, validates configuration without processing documents.")
    source_collection_id: Optional[StrictStr] = Field(default=None, description="Collection reference (for context/logging only in ON_DEMAND mode)")
    target_collection_id: Optional[StrictStr] = Field(default=None, description="Not used in ON_DEMAND mode.")
    join_mode: Optional[JoinMode] = Field(default=None, description="Must be `on_demand`. Batch mode is not supported via API.")
    batch_size: Optional[Annotated[int, Field(le=10000, strict=True, ge=1)]] = Field(default=1000, description="Batch size for the scroll iterator")
    scroll_filters: Optional[LogicalOperatorInput] = Field(default=None, description="Additional filters applied to the source collection prior to enrichment.")
    __properties: ClassVar[List[str]] = ["taxonomy", "retriever", "source_documents", "source_collection_id", "target_collection_id", "join_mode", "batch_size", "scroll_filters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecuteTaxonomyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of taxonomy
        if self.taxonomy:
            _dict['taxonomy'] = self.taxonomy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of retriever
        if self.retriever:
            _dict['retriever'] = self.retriever.to_dict()
        # override the default output from pydantic by calling `to_dict()` of scroll_filters
        if self.scroll_filters:
            _dict['scroll_filters'] = self.scroll_filters.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecuteTaxonomyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "taxonomy": TaxonomyModel.from_dict(obj["taxonomy"]) if obj.get("taxonomy") is not None else None,
            "retriever": RetrieverModelInput.from_dict(obj["retriever"]) if obj.get("retriever") is not None else None,
            "source_documents": obj.get("source_documents"),
            "source_collection_id": obj.get("source_collection_id"),
            "target_collection_id": obj.get("target_collection_id"),
            "join_mode": obj.get("join_mode"),
            "batch_size": obj.get("batch_size") if obj.get("batch_size") is not None else 1000,
            "scroll_filters": LogicalOperatorInput.from_dict(obj["scroll_filters"]) if obj.get("scroll_filters") is not None else None
        })
        return _obj


