# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExtractorDiscovery(BaseModel):
    """
    Feature extractor discovery information.  Provides comprehensive information about a feature extractor for agent-driven configuration and manifest generation.
    """ # noqa: E501
    name: StrictStr = Field(description="Feature extractor name (e.g., 'multimodal_extractor')")
    version: StrictStr = Field(description="Feature extractor version (e.g., 'v1')")
    description: StrictStr = Field(description="Human-readable description of what this extractor does")
    supported_modalities: Optional[List[StrictStr]] = Field(default=None, description="List of supported input modalities (text, image, video, audio)")
    output_features: Optional[List[Dict[str, Any]]] = Field(default=None, description="List of features produced by this extractor")
    input_schema: Optional[Dict[str, Any]] = Field(default=None, description="JSON Schema for extractor input parameters")
    example_usage: Optional[Dict[str, Any]] = Field(default=None, description="Example manifest YAML snippet showing how to use this extractor")
    __properties: ClassVar[List[str]] = ["name", "version", "description", "supported_modalities", "output_features", "input_schema", "example_usage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExtractorDiscovery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExtractorDiscovery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "version": obj.get("version"),
            "description": obj.get("description"),
            "supported_modalities": obj.get("supported_modalities"),
            "output_features": obj.get("output_features"),
            "input_schema": obj.get("input_schema"),
            "example_usage": obj.get("example_usage")
        })
        return _obj


