# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mixpeek.models.lifecycle_state import LifecycleState
from typing import Optional, Set
from typing_extensions import Self

class LifecycleStatusResponse(BaseModel):
    """
    LifecycleStatusResponse
    """ # noqa: E501
    collection_id: StrictStr
    lifecycle_state: LifecycleState
    s3_vector_index: Optional[StrictStr] = None
    qdrant_document_count: Optional[StrictInt] = None
    s3_vector_count: Optional[StrictInt] = None
    last_transitioned_at: Optional[datetime] = None
    task_id: Optional[StrictStr] = None
    warning: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["collection_id", "lifecycle_state", "s3_vector_index", "qdrant_document_count", "s3_vector_count", "last_transitioned_at", "task_id", "warning"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LifecycleStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LifecycleStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "collection_id": obj.get("collection_id"),
            "lifecycle_state": obj.get("lifecycle_state"),
            "s3_vector_index": obj.get("s3_vector_index"),
            "qdrant_document_count": obj.get("qdrant_document_count"),
            "s3_vector_count": obj.get("s3_vector_count"),
            "last_transitioned_at": obj.get("last_transitioned_at"),
            "task_id": obj.get("task_id"),
            "warning": obj.get("warning")
        })
        return _obj


