# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from mixpeek.models.group_by_option import GroupByOption
from mixpeek.models.logical_operator_input import LogicalOperatorInput
from mixpeek.models.sort_option import SortOption
from typing import Optional, Set
from typing_extensions import Self

class RetrieverQueryRequest(BaseModel):
    """
    Query parameters for executing a retriever pipeline.  This model defines all the parameters that can be provided when running a search using a predefined retriever pipeline. It allows for customizing the query inputs, filtering, sorting, pagination, and result formatting.
    """ # noqa: E501
    retriever_id: Optional[StrictStr] = Field(default=None, description="Identifier of the retriever to execute. If omitted, the execution context must provide it.")
    inputs: Dict[str, Any] = Field(description="Input values for the retriever query. These map to the required inputs defined in the retriever's first stage.")
    filters: Optional[LogicalOperatorInput] = Field(default=None, description="Logical operations for filtering results. Can include AND, OR, NOT conditions with field comparisons.")
    sorts: Optional[List[SortOption]] = Field(default=None, description="Controls the ordering of results. Can sort by score (default) or any other document field. This sorts the results from the last stage.")
    limit: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=10, description="Maximum number of results to return. Overrides the default pagination limit in the retriever definition.")
    offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=0, description="Number of results to skip. Use with limit for pagination. For large offsets, consider using session_id for cursor-based pagination.")
    select: Optional[List[StrictStr]] = Field(default=None, description="Specific fields to include in the response. If not specified, returns all fields.")
    session_id: Optional[StrictStr] = Field(default=None, description="Session identifier for interaction tracking.")
    return_urls: Optional[StrictBool] = Field(default=False, description="When true, generates pre-signed URLs for any media assets in the results. May increase response time slightly.")
    group_by: Optional[GroupByOption] = Field(default=None, description="Options for grouping results by a specific field.")
    __properties: ClassVar[List[str]] = ["retriever_id", "inputs", "filters", "sorts", "limit", "offset", "select", "session_id", "return_urls", "group_by"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetrieverQueryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filters
        if self.filters:
            _dict['filters'] = self.filters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sorts (list)
        _items = []
        if self.sorts:
            for _item_sorts in self.sorts:
                if _item_sorts:
                    _items.append(_item_sorts.to_dict())
            _dict['sorts'] = _items
        # override the default output from pydantic by calling `to_dict()` of group_by
        if self.group_by:
            _dict['group_by'] = self.group_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetrieverQueryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "retriever_id": obj.get("retriever_id"),
            "inputs": obj.get("inputs"),
            "filters": LogicalOperatorInput.from_dict(obj["filters"]) if obj.get("filters") is not None else None,
            "sorts": [SortOption.from_dict(_item) for _item in obj["sorts"]] if obj.get("sorts") is not None else None,
            "limit": obj.get("limit") if obj.get("limit") is not None else 10,
            "offset": obj.get("offset") if obj.get("offset") is not None else 0,
            "select": obj.get("select"),
            "session_id": obj.get("session_id"),
            "return_urls": obj.get("return_urls") if obj.get("return_urls") is not None else False,
            "group_by": GroupByOption.from_dict(obj["group_by"]) if obj.get("group_by") is not None else None
        })
        return _obj


