# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81.1
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from mixpeek.models.value2 import Value2
from typing import Optional, Set
from typing_extensions import Self

class StageDefsVectorQueryInput(BaseModel):
    """
    Raw embedding vector query input for direct vector similarity search.  Accepts a pre-computed embedding vector and uses it directly for similarity search without any inference. Useful for programmatic use cases such as taxonomy enrichment where embeddings are already available.  Use Cases:     - Taxonomy enrichment (passing pre-computed document embeddings)     - Programmatic similarity search with known vectors     - Cross-collection matching with pre-extracted features     - ColBERT/multi-vector search with pre-computed token embeddings  Examples:     Single dense vector:         ```json         {\"input_mode\": \"vector\", \"value\": [0.1, 0.2, 0.3, ...]}         ```      Multi-dense vector (ColBERT — list of token embeddings):         ```json         {\"input_mode\": \"vector\", \"value\": [[0.1, 0.2], [0.3, 0.4], ...]}         ```      Template-based (from taxonomy input mapping):         ```json         {\"input_mode\": \"vector\", \"value\": \"{{INPUT.query_image}}\"}         ```
    """ # noqa: E501
    input_mode: Optional[StrictStr] = Field(default='vector', description="Discriminator field. Always 'vector' for raw embedding queries.")
    value: Optional[Value2] = None
    __properties: ClassVar[List[str]] = ["input_mode", "value"]

    @field_validator('input_mode')
    def input_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['vector']):
            raise ValueError("must be one of enum values ('vector')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StageDefsVectorQueryInput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of value
        if self.value:
            _dict['value'] = self.value.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StageDefsVectorQueryInput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "input_mode": obj.get("input_mode") if obj.get("input_mode") is not None else 'vector',
            "value": Value2.from_dict(obj["value"]) if obj.get("value") is not None else None
        })
        return _obj


