# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class TSNEParams(BaseModel):
    """
    TSNEParams
    """ # noqa: E501
    method: Optional[StrictStr] = 'tsne'
    n_components: Optional[Annotated[int, Field(le=256, strict=True, ge=2)]] = 2
    random_state: Optional[StrictInt] = 42
    perplexity: Optional[Union[StrictFloat, StrictInt]] = 30.0
    learning_rate: Optional[Union[StrictFloat, StrictInt]] = 200.0
    __properties: ClassVar[List[str]] = ["method", "n_components", "random_state", "perplexity", "learning_rate"]

    @field_validator('method')
    def method_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['tsne']):
            raise ValueError("must be one of enum values ('tsne')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TSNEParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TSNEParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "method": obj.get("method") if obj.get("method") is not None else 'tsne',
            "n_components": obj.get("n_components") if obj.get("n_components") is not None else 2,
            "random_state": obj.get("random_state") if obj.get("random_state") is not None else 42,
            "perplexity": obj.get("perplexity") if obj.get("perplexity") is not None else 30.0,
            "learning_rate": obj.get("learning_rate") if obj.get("learning_rate") is not None else 200.0
        })
        return _obj


