# coding: utf-8

"""
    Mixpeek API

    This is the Mixpeek API, providing access to various endpoints for data processing and retrieval.

    The version of the OpenAPI document: 0.81
    Contact: info@mixpeek.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from mixpeek.models.bucket_schema_field_type import BucketSchemaFieldType
from mixpeek.models.vector_data_type import VectorDataType
from mixpeek.models.vector_type import VectorType
from typing import Optional, Set
from typing_extensions import Self

class VectorIndex(BaseModel):
    """
    Base configuration for vector indexes.
    """ # noqa: E501
    name: StrictStr
    description: StrictStr
    dimensions: StrictInt
    type: VectorType
    distance: Optional[StrictStr] = 'cosine'
    datatype: Optional[VectorDataType] = Field(default=None, description="Data type of the vector.")
    on_disk: Optional[StrictBool] = Field(default=None, description="If true, vectors will be stored on disk. Use for large vectors.")
    supported_inputs: Optional[List[BucketSchemaFieldType]] = None
    inference_name: Optional[StrictStr] = Field(default=None, description="The path to the embedding model service to use for this vector index.")
    __properties: ClassVar[List[str]] = ["name", "description", "dimensions", "type", "distance", "datatype", "on_disk", "supported_inputs", "inference_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VectorIndex from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VectorIndex from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "dimensions": obj.get("dimensions"),
            "type": obj.get("type"),
            "distance": obj.get("distance") if obj.get("distance") is not None else 'cosine',
            "datatype": obj.get("datatype"),
            "on_disk": obj.get("on_disk"),
            "supported_inputs": obj.get("supported_inputs"),
            "inference_name": obj.get("inference_name")
        })
        return _obj


