workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Mixpeek API:
        inputs:
            - location: https://server-xb24.onrender.com/docs/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: security_overlay.yml
        registry:
            location: registry.speakeasyapi.dev/mixpeek/api/mixpeek-api
targets:
    mixpeek:
        target: python
        source: Mixpeek API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mixpeek/api/mixpeek-api-python-code-samples
            labelOverride:
                fixedValue: Python Client
            blocking: false
